/* Generated By:JavaCC: Do not edit this line. RobocupCmdParserConstants.java */
package roboILP;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobocupCmdParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BALL = 4;
  /** RegularExpression Id. */
  int FLAG = 5;
  /** RegularExpression Id. */
  int PLAYER = 6;
  /** RegularExpression Id. */
  int LINE = 7;
  /** RegularExpression Id. */
  int GOAL = 8;
  /** RegularExpression Id. */
  int UNK_GOAL = 9;
  /** RegularExpression Id. */
  int REFEREE = 10;
  /** RegularExpression Id. */
  int SELF = 11;
  /** RegularExpression Id. */
  int VIEW_MODE = 12;
  /** RegularExpression Id. */
  int HIGH = 13;
  /** RegularExpression Id. */
  int LOW = 14;
  /** RegularExpression Id. */
  int WIDE = 15;
  /** RegularExpression Id. */
  int NARROW = 16;
  /** RegularExpression Id. */
  int NORMAL = 17;
  /** RegularExpression Id. */
  int STAMINA = 18;
  /** RegularExpression Id. */
  int SPEED = 19;
  /** RegularExpression Id. */
  int HEAD_ANGLE = 20;
  /** RegularExpression Id. */
  int KICK = 21;
  /** RegularExpression Id. */
  int DASH = 22;
  /** RegularExpression Id. */
  int TURN = 23;
  /** RegularExpression Id. */
  int SAY = 24;
  /** RegularExpression Id. */
  int TURN_NECK = 25;
  /** RegularExpression Id. */
  int BEFORE_KICK_OFF = 26;
  /** RegularExpression Id. */
  int TIME_OVER = 27;
  /** RegularExpression Id. */
  int PLAY_ON = 28;
  /** RegularExpression Id. */
  int DROP_BALL = 29;
  /** RegularExpression Id. */
  int KICK_OFF_L = 30;
  /** RegularExpression Id. */
  int KICK_OFF_R = 31;
  /** RegularExpression Id. */
  int KICK_IN_L = 32;
  /** RegularExpression Id. */
  int KICK_IN_R = 33;
  /** RegularExpression Id. */
  int FREE_KICK_R = 34;
  /** RegularExpression Id. */
  int FREE_KICK_L = 35;
  /** RegularExpression Id. */
  int FREE_KICK_FAULT_R = 36;
  /** RegularExpression Id. */
  int FREE_KICK_FAULT_L = 37;
  /** RegularExpression Id. */
  int CORNER_KICK_R = 38;
  /** RegularExpression Id. */
  int CORNER_KICK_L = 39;
  /** RegularExpression Id. */
  int GOAL_KICK_R = 40;
  /** RegularExpression Id. */
  int GOAL_KICK_L = 41;
  /** RegularExpression Id. */
  int GOAL_R = 42;
  /** RegularExpression Id. */
  int GOAL_L = 43;
  /** RegularExpression Id. */
  int FOUL_R = 44;
  /** RegularExpression Id. */
  int FOUL_L = 45;
  /** RegularExpression Id. */
  int OFFSIDE_R = 46;
  /** RegularExpression Id. */
  int OFFSIDE_L = 47;
  /** RegularExpression Id. */
  int HALF_TIME = 48;
  /** RegularExpression Id. */
  int TIME_UP = 49;
  /** RegularExpression Id. */
  int TIME_UP_WITHOUT_A_TEAM = 50;
  /** RegularExpression Id. */
  int TIME_EXTENDED = 51;
  /** RegularExpression Id. */
  int INIT = 52;
  /** RegularExpression Id. */
  int OB = 53;
  /** RegularExpression Id. */
  int CB = 54;
  /** RegularExpression Id. */
  int SEP = 55;
  /** RegularExpression Id. */
  int NAN = 56;
  /** RegularExpression Id. */
  int NAM = 57;
  /** RegularExpression Id. */
  int NUM = 58;
  /** RegularExpression Id. */
  int PARAM_1A = 59;
  /** RegularExpression Id. */
  int PARAM_1A_1N = 60;
  /** RegularExpression Id. */
  int PARAM_2A = 61;
  /** RegularExpression Id. */
  int PARAM_2A_1N = 62;
  /** RegularExpression Id. */
  int PARAM_3A = 63;
  /** RegularExpression Id. */
  int ALPH = 64;
  /** RegularExpression Id. */
  int QUOTE = 65;
  /** RegularExpression Id. */
  int EMPTY = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BALL>",
    "<FLAG>",
    "<PLAYER>",
    "<LINE>",
    "<GOAL>",
    "\"Goal\"",
    "<REFEREE>",
    "\"self\"",
    "\"view_mode\"",
    "\"high\"",
    "\"low\"",
    "\"wide\"",
    "\"narrow\"",
    "\"normal\"",
    "\"stamina\"",
    "\"speed\"",
    "\"head_angle\"",
    "\"kick\"",
    "\"dash\"",
    "\"turn\"",
    "\"say\"",
    "\"turn_neck\"",
    "\"before_kick_off\"",
    "\"time_over\"",
    "\"play_on\"",
    "\"drop_ball\"",
    "\"kick_off_l\"",
    "\"kick_off_r\"",
    "\"kick_in_l\"",
    "\"kick_in_r\"",
    "\"free_kick_r\"",
    "\"free_kick_l\"",
    "\"free_kick_fault_r\"",
    "\"free_kick_fault_l\"",
    "\"corner_kick_r\"",
    "\"corner_kick_l\"",
    "\"goal_kick_r\"",
    "\"goal_kick_l\"",
    "<GOAL_R>",
    "<GOAL_L>",
    "\"foul_r\"",
    "\"foul_l\"",
    "\"offside_r\"",
    "\"offside_l\"",
    "\"half_time\"",
    "\"time_up\"",
    "\"time_up_without_a_team\"",
    "\"time_extended\"",
    "<INIT>",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"nan\"",
    "<NAM>",
    "<NUM>",
    "<PARAM_1A>",
    "<PARAM_1A_1N>",
    "<PARAM_2A>",
    "<PARAM_2A_1N>",
    "<PARAM_3A>",
    "<ALPH>",
    "\"\\\"\"",
    "<EMPTY>",
  };

}
